var namespace_local_server_1_1_g_u_i_1_1_view_1_1_code___behind_1_1_user_authentication_window_1_1_pages =
[
    [ "BridgeAPILoginPage", "class_local_server_1_1_g_u_i_1_1_view_1_1_code___behind_1_1_user_authentication_window_1_1_pages_1_1_bridge_a_p_i_login_page.html", "class_local_server_1_1_g_u_i_1_1_view_1_1_code___behind_1_1_user_authentication_window_1_1_pages_1_1_bridge_a_p_i_login_page" ]
];